### PR TITLE
cfp: Replace "online" with "on-campus"

### PR DESCRIPTION
**Pull request by mpsijm**
~~Also replaced "judge" with "jury"~~

### CODE REVIEW

**Comment by verwoerd** [comment]
why change judge to jury?  A person is never a jury by it self. This is the official terminology of ICPC, who even doesn't know the concept of jury but always speaks of judges (e.g. https://icpc.global/worldfinals/rules and https://icpc.global/regionals/rules). Since NWERC is bound by the regional rules I would advise to follow the terminology used in the ICPC rules.

**Comment by mpsijm** [comment]
Fair enough. In my mind, "jury" are people and "judges" are machines, but let's stick with official terminology indeed :slightly_smiling_face:

**Comment by verwoerd** [comment]
I left the option for online in since we don't know what will happen in the winter, but lets stay optimistic :)

**Comment by mpsijm** [comment]
That's why the text says "_expected_ to take place on-campus" :wink:

**Pull request merged**
